services:
  code-server:
    image: ghcr.io/xvzhenduo/dev-env:latest
    container_name: code-server
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - GIT_USER_NAME=example
      - GIT_USER_EMAIL=example@example.com
    volumes:
      - ./local:/home/coder/.local
      - ./config:/home/coder/.config
      - ./project:/home/coder/project